### ISSUE TITLE
 API Gateway rewrite URL

### ISSUE THREAD

**Issue by typexy** [googleapis/java-api-gateway#332]
Hi,

what is the best way to proxy requests with GCP API Gateway, e.g. to hide secrets?

A sample request to "transform" might be:

Client -> XXX (API-Gateway)  -> External Service

       -> https://api.xxx.com/xxx            -> https://api.xxx.com/xxx?secret=secret

Unfortunately, I couldn't find an example nor support in a [stackoverflow post.](https://stackoverflow.com/questions/73933712/whats-the-best-way-to-proxy-requests-with-gcp)

Many thanks in advance.

Do you have by any chance an example or a hint?

**Comment by suztomo** [comment]
You have gotten the answer in the stackoverflow post.
